name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag cbarria/rubinstars
        docker login -u cbarria -p a2d0de25-08c8-4b41-8fc2-7d8dca41c0ed
        docker push cbarria/rubinstars
